// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Approval probability prediction
 */
export type ApprovalPrediction = { probability: number, should_auto_approve: boolean, rationale: string, };