// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk score for an incident or decision
 */
export type RiskScore = { score: number, severity: string, factors: Array<string>, };